### ISSUE TITLE
4.0.0 throws exceptions getSegmentByNavIdOrName is not a function

### ISSUE THREAD

**Issue by longdw** [zyra/ionic2-super-tabs#123]
```
Error: Uncaught (in promise): TypeError: this.linker.getSegmentByNavIdOrName is not a function
TypeError: this.linker.getSegmentByNavIdOrName is not a function
    at SuperTabs.ngAfterViewInit (http://localhost:8101/build/main.js:56814:39)
    at callProviderLifecycles (http://localhost:8101/build/main.js:11521:18)
    at callElementProvidersLifecycles (http://localhost:8101/build/main.js:11496:13)
    at callLifecycleHooksChildrenFirst (http://localhost:8101/build/main.js:11480:17)
    at checkAndUpdateView (http://localhost:8101/build/main.js:12512:5)
    at callViewAction (http://localhost:8101/build/main.js:12867:21)
    at execEmbeddedViewsAction (http://localhost:8101/build/main.js:12825:17)
    at checkAndUpdateView (http://localhost:8101/build/main.js:12505:5)
    at callViewAction (http://localhost:8101/build/main.js:12867:21)
    at execComponentViewsAction (http://localhost:8101/build/main.js:12799:13)
    at c (http://localhost:8101/build/polyfills.js:3:13190)
    at Object.reject (http://localhost:8101/build/polyfills.js:3:12546)
    at NavControllerBase._fireError (http://localhost:8101/build/main.js:44350:16)
    at NavControllerBase._failed (http://localhost:8101/build/main.js:44338:14)
    at http://localhost:8101/build/main.js:44393:59
    at t.invoke (http://localhost:8101/build/polyfills.js:3:8971)
    at Object.onInvoke (http://localhost:8101/build/main.js:4509:37)
    at t.invoke (http://localhost:8101/build/polyfills.js:3:8911)
    at r.run (http://localhost:8101/build/polyfills.js:3:4140)
    at http://localhost:8101/build/polyfills.js:3:13731
```

**Comment by ihadeed** [comment]
Check compatibility table in this repo's home page.
You're probably using `ionic-angular@3.5.0` with `ionic2-super-tabs@4.0.0`

**Comment by longdw** [comment]
@ihadeed Awesome, thanks!
