### ISSUE TITLE
issue with installing

### ISSUE THREAD

**Issue by mrqaidi** [zyra/ionic2-super-tabs#130]
Hi

i am getting this issue

`Runtime Error
Uncaught (in promise): TypeError: this.linker.initNav is not a function TypeError: this.linker.initNav is not a function at SuperTabs.ngAfterViewInit (http://localhost:8100/build/main.js:66929:39) at callProviderLifecycles (http://localhost:8100/build/main.js:11439:18) at callElementProvidersLifecycles (http://localhost:8100/build/main.js:11414:13) at callLifecycleHooksChildrenFirst (http://localhost:8100/build/main.js:11398:17) at checkAndUpdateView (http://localhost:8100/build/main.js:12430:5) at callViewAction (http://localhost:8100/build/main.js:12785:21) at execComponentViewsAction (http://localhost:8100/build/main.js:12717:13) at checkAndUpdateView (http://localhost:8100/build/main.js:12428:5) at callWithDebugContext (http://localhost:8100/build/main.js:13484:42) at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:8100/build/main.js:13024:12)`

**Comment by mrqaidi** [comment]
issue fixed by changing  version of ionic2-super-tabs  to 4.0.0 in package.json
