### ISSUE TITLE
Uncaught (in promise): invalid views to insert

### ISSUE THREAD

**Issue by ZhenweiZhang1995** [zyra/ionic2-super-tabs#182]
I got error when trying to add super tab tags, can anyone help me with that?

Error: Uncaught (in promise): invalid views to insert
    at c (http://localhost:8100/build/polyfills.js:3:19132)
    at http://localhost:8100/build/polyfills.js:3:18554
    at rejected (http://localhost:8100/build/vendor.js:57876:89)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14356)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4247:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14296)
    at r.run (http://localhost:8100/build/polyfills.js:3:9523)
    at http://localhost:8100/build/polyfills.js:3:19622
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15040)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4238:33)

**Comment by ihadeed** [comment]
Did you pass a valid component to be used as the tab root?

Can you share your code?

**Comment by ZhenweiZhang1995** [comment]
This is in the home.html and there is nothing in home.ts

**Comment by ZhenweiZhang1995** [comment]
Okay I figured it out. Thanks!

**Comment by alpamys-qanybet** [comment]
@ZhenweiZhang1995, so what was the problem?, I have the same error.

**Comment by sfance** [comment]
@ZhenweiZhang1995 do you mind posting your solution?

**Comment by tamilm47** [comment]
I am also having the same issue.Please post the solution
