### ISSUE TITLE
Error when building prod release: Metadata version mismatch for module... found version 4, expected 3 

### ISSUE THREAD

**Issue by elbidone** [zyra/ionic2-super-tabs#241]
Hi,

when I try to build app for prod it raises an error for ionic2-super-tabs module

```
$ npm run ionic:build --prod

> ionic-app-scripts build 

[12:17:12]  ionic-app-scripts 2.1.3 
[12:17:12]  build prod started ... 
[12:17:12]  clean started ... 
[12:17:13]  clean finished in 194 ms 
[12:17:13]  copy started ... 
[12:17:13]  ngc started ... 
[12:17:24]  ionic-app-script task: "build" 
[12:17:24]  Error: Metadata version mismatch for module 
            /Users/victor/Dvpt/PROJECTS/ion-employee/node_modules/ionic2-super-tabs/dist/providers/super-tabs-controller.d.ts,
            found version 4, expected 3 
Error: Metadata version mismatch for module /Users/victor/Dvpt/PROJECTS/ion-employee/node_modules/ionic2-super-tabs/dist/providers/super-tabs-controller.d.ts, found version 4, expected 3
...
```
Works well on development mode.

Below my configuration

```
$ npm ls --depth 0
├── @angular/common@4.1.3
├── @angular/compiler@4.1.3
├── @angular/compiler-cli@4.1.3
├── @angular/core@4.1.3
├── @angular/forms@4.1.3
├── @angular/http@4.1.3
├── @angular/platform-browser@4.1.3
├── @angular/platform-browser-dynamic@4.1.3
├── @ionic-native/core@3.12.1
├── @ionic-native/splash-screen@3.12.1
├── @ionic-native/status-bar@3.12.1
├── @ionic/app-scripts@2.1.3
├── @ionic/storage@2.0.1
├── @ngx-translate/core@7.2.2
├── @ngx-translate/http-loader@0.1.0
├── angular-moment@1.2.0
├── angular2-moment@1.7.1
├── angularfire2@4.0.0-rc0
├── cordova-android@6.4.0
├── cordova-plugin-console@1.1.0
├── cordova-plugin-device@1.1.7
├── cordova-plugin-splashscreen@4.1.0
├── cordova-plugin-statusbar@2.4.0
├── cordova-plugin-whitelist@1.3.3
├── firebase@3.9.0
├── ionic-angular@3.9.2
├── ionic-plugin-keyboard@2.2.1
├── ionic2-super-tabs@4.1.5
├── ionicons@3.0.0
├── moment@2.20.1
├── rxjs@5.4.0
├── sw-toolbox@3.6.0
├── typescript@2.3.4
└── zone.js@0.8.12
```

**Comment by ivanosire** [comment]
Same problem. Maybe the problem is the angular version 4.1.3 ?!?

`Error: Metadata version mismatch for module C:/***/node_modules/ionic2-super-tabs/dist/providers/super-tabs-controller.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (C:\***\node_modules\@angular\compiler\bundles\compiler.umd.js:24474:34)
    at StaticSymbolResolver._createSymbolsOf (C:\***\node_modules\@angular\compiler\bundles\compiler.umd.js:24260:46)
    at StaticSymbolResolver.getSymbolsOf (C:\***\node_modules\@angular\compiler\bundles\compiler.umd.js:24241:14)
    at C:\***\node_modules\@angular\compiler\bundles\compiler.umd.js:23023:30
    at Array.forEach (native)
    at extractProgramSymbols (C:\***\node_modules\@angular\compiler\bundles\compiler.umd.js:23022:79)
    at AotCompiler.compileAll (C:\***\node_modules\@angular\compiler\bundles\compiler.umd.js:22720:47)
    at CodeGenerator.codegen (C:\***\node_modules\@angular\compiler-cli\src\codegen.js:30:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\***\node_modules\@angular\compiler-cli\src\ngtools_api.js:61:30)
    at C:\***\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:182:73`

**Comment by elbidone** [comment]
I've also tested with angular 4.4.6, but didn't work

**Comment by ihadeed** [comment]
Latest version is compiled with Angular 5, which has no backwards compatibility. I will build t he next release with Angular 4 so we can support all angular versions again. Publishing a new version  tonight.. stay tuned.

**Comment by junobartowski** [comment]
I just encountered this error... Anyone has a solution? Thanks!
