### ISSUE TITLE
Error when initializing tabs in Ionic 2

### ISSUE THREAD

**Issue by JeremyLopez** [zyra/ionic2-super-tabs#86]
```
Error: Uncaught (in promise): TypeError: this._renderer.setElementStyle is not a function
TypeError: this._renderer.setElementStyle is not a function
    at SuperTab.Ion.setElementStyle (http://localhost:8100/build/main.js:19594:24)
    at SuperTab.setWidth (http://localhost:8100/build/main.js:171714:14)
    at SuperTabs.addTab (http://localhost:8100/build/main.js:171192:13)
    at SuperTab.ngOnInit (http://localhost:8100/build/main.js:171673:21)
    at checkAndUpdateDirectiveInline (http://localhost:8100/build/main.js:11039:19)
    at checkAndUpdateNodeInline (http://localhost:8100/build/main.js:12417:17)
    at checkAndUpdateNode (http://localhost:8100/build/main.js:12385:16)
    at prodCheckAndUpdateNode (http://localhost:8100/build/main.js:12838:5)
    at Object.View_ClientGenericPage_1.co [as updateDirectives] (ng:///AppModule/ClientGenericPage.ngfactory.js:321:5)
    at Object.updateDirectives (http://localhost:8100/build/main.js:12753:72)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12352:14)
    at callViewAction (http://localhost:8100/build/main.js:12667:17)
    at execEmbeddedViewsAction (http://localhost:8100/build/main.js:12639:17)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12353:5)
    at callViewAction (http://localhost:8100/build/main.js:12667:17)
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at l (http://localhost:8100/build/polyfills.js:3:6251)
    at http://localhost:8100/build/polyfills.js:3:6805
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15213)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4416:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15134)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:10390)
    at a (http://localhost:8100/build/polyfills.js:3:5313)
    at XMLHttpRequest.invoke (http://localhost:8100/build/polyfills.js:3:16210)
```

^ this is the error I see when I try to load the page with the tabs on it.  Here is ther rest of my component:

```
@Component({
  templateUrl: 'client-generic.html',
  selector: 'client-generic',
  providers: [SuperTabsModule]
})

export class ClientGenericPage {
  constructor(
    public navCtrl: NavController, 
    public navParams: NavParams, 
    public modalController: ModalController,
    private clientService: ClientService) {
        // set local variables
    }
}
```

**Comment by ihadeed** [comment]
The latest version of this module works only with `ionic-angular@3.4.x` ... if you are still using an earlier version ,please downgrade to at least `ionic2-super-tabs@2.6.2` ..

See release notes for more info https://github.com/zyra/ionic2-super-tabs/releases
